[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "open-source-cai-pipecat-core"
version = "0.1.0"
authors = [
    { name="Aniket-think41" }
]
description = "Core package for Open Source CAI Pipecat"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["ai", "pipecat", "open-source"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Aniket-think41/Open-Source-CAI-Pipecat"


[tool.setuptools.package-data]
"open_source_cai_pipecat_core" = ["*.py", "*.txt", "*.md"]

[tool.setuptools.dynamic]
version = { attr = "open_source_cai_pipecat_core.__version__" }


[tool.setuptools.packages.find]
where = ["."]
include = ["open_source_cai_pipecat_core"]
exclude = ["tests", "docs"]

