[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "foundational-ai-server"
version = "0.1.0"
authors = [
    { name="think41" }
]
description = "Foundational AI Server"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["ai", "foundational-ai", "open-source"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/think41/foundational-ai-server"


[tool.setuptools.package-data]
"foundational_ai_server" = ["*.py", "*.txt", "*.md"]

[tool.setuptools.dynamic]
version = { attr = "foundational_ai_server.__version__" }


[tool.setuptools.packages.find]
where = ["."]
include = ["foundational_ai_server"]
exclude = ["tests", "docs"]

